spring:
  git:
    userName: limeng000111
    password: LiMeng123456
    local:
      base:
        dir: E:\diff

  svn:
    userName:
    password:
    local:
      base:
        dir:

#server:
#  port: 8081